---
title: "Blog Post 1"
---

In the introduction of *Data Feminism* [^1], the author talks about that despite her qualifications, Darden was not promoted to the same positions as her male counterparts due to discriminations against her identity as a female. While Darden was fully aware of the oppression she experienced, it was not until Champine compiled and presented the statistics about gender and rank to the director of Darden’s division that the male director finally believed the long-existing gender disparity in the workplace. This example of using data to demonstrate the collective experience of oppression immediately reminds me a paper that reveals implicit bias in academia. The study asked science faculty to rate the application materials of a student with either a male (John) or female (Jennifer) name for a lab manager position [^2]. Results showed that faculty rated male participants as significantly more hirable than female counterparts with the same qualification, and the discrepancy could be explained by faculty perceiving female applicants as less competent. I firstly encountered this study in the course Psychology of Women and Gender and was amazed by how carefully-designed studies were able to provide evidence on social inequalities and reveal the double or multiple oppressions experienced by people with intersecting identities [^3]. By raising theory-driven questions and contextualizing data, these analysis challenges the existing power structures and call for actions. 


As the authors point out, **“data never, ever speak for themselves.”** Many people view data as “objective fact” but in reality it definitely is not if we think about what/whose data is collected, how it is analyzed, and who makes the interpretations. Last year, an article published in Nature Communications claims that having a female mentor is associated with decrease in outcomes for mentees, and a female mentor publishes less by mentoring female instead of male mentees [^4]. The study blatantly concludes that “while current diversity policies encourage same-gender mentorships to retain women in academia, our findings raise the possibility that opposite-gender mentorship may actually increase the impact of women who pursue a scientific career.” It’s extremely harmful when the authors have poor study design and completely ignore barriers to academic success but somehow believe big data can magically yield the most “accurate” results. There are many critiques to the methodology of that paper, but one thing I am thinking about is how to quantify people’s experiences and identities. D’lgnazio and Klein wrote that “the process of converting life experience into data always necessarily entails a reduction of that experience.” In quantitative research, often times gender and race/ethncity are measured by variables simply asking what gender and race/ethncity one identifies with. However, results such as “female applicants are viewed less hirable” and “BIPOC are more likely to get infected with COVID”, when interpreted without contexts, do not necessarily encapsulate the social constructs of these identities and the sexism and racism one might experience. In fact, scholars have reflected on why racism instead of race being the risk factor of poor health outcomes [^5]. The question of how to quantify living experience and contexuliaze results is definitely something I will continue to learn about and think about in my work. 

[^1]: Introduction: Why Data Science Needs Feminism. (2020). In Data Feminism. Retrieved from https://data-feminism.mitpress.mit.edu/pub/frfa9szd

[^2]: Moss-Racusin, C. A., Dovidio, J. F., Brescoll, V. L., Graham, M. J., & Handelsman, J. (2012). Science faculty’s subtle gender biases favor male students. Proceedings of the national academy of sciences, 109(41), 16474-16479. https://www.pnas.org/content/109/41/16474.short


[^3]: Eaton, A. A., Saunders, J. F., Jacobson, R. K., & West, K. (2020). How gender and race stereotypes impact the advancement of scholars in STEM: Professors’ biased evaluations of physics and biology post-doctoral candidates. Sex Roles, 82(3), 127-141. https://link.springer.com/article/10.1007/s11199-019-01052-w

[^4]: AlShebli, B., Makovi, K., & Rahwan, T. (2020). RETRACTED ARTICLE: The association between early career informal mentorship in academic collaborations and junior author performance. Nature communications, 11(1), 1-8. https://www.nature.com/articles/s41467-020-19723-8 

[^5]: Wallis, Claudia. (2020). Why Racism, Not Race, Is a Risk Factor for Dying of COVID-19. Scientific American. Retrieved from https://www.scientificamerican.com/article/why-racism-not-race-is-a-risk-factor-for-dying-of-covid-191/

